#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷‍♂️ Styling, testing, and building your project before committing'


echo '🏗️ Running ESLint and Prettier...'

# Fix ESLint and Prettier formatting
yarn eslint --fix . || exit 1
yarn format
# Check TypeScript standards
yarn check-types ||
(
    echo '❌ Failed Type check ❌
    Please fix the type errors before committing.
    You can use `yarn types` to fix the errors, add the changes, and commit again.'
    false;
)

# Check Prettier standards
yarn check-format ||
(
    echo '❌ Failed Prettier check ❌
    Please fix the prettier errors before committing. 
    You can use `yarn format` to fix the errors, add the changes, and commit again.'
    false;
)

# Check ESLint standards
yarn check-lint ||
(
    echo '❌ Failed ESLint check ❌
    Please fix the ESLint errors before committing. 
    You can use `yarn lint` to fix the errors, add the changes, and commit again.'
    false;
)

# Check Jest tests
yarn test ||
(
    echo '❌ Failed Jest check ❌
    Please fix the Jest errors before committing. 
    You can use `yarn test` to fix the errors, add the changes, and commit again.'
    false;
)

# If all checks pass, build the project
yarn build ||
(
    echo '❌ Failed Build ❌
    Please fix the build errors before committing. 
    You can use `yarn build` to fix the errors, add the changes, and commit again.'
    false;
)

# If the build is successful, commit the changes
echo '✅ All checks passed. Committing changes...'
