#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷‍♂️ Styling, testing and building your project before committing'

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed Type check ❌
    Please fix the type errors before committing.
    You can use `npm run types` to fix the errors, add the changes and commit again.'
    false;
)

# Check Prettier standards
npm run check-format ||
(
    echo '❌ Failed Prettier check ❌
    Please fix the prettier errors before committing. 
    You can use `npm run format` to fix the errors, add the changes and commit again.'
    false;
)

# Check ESLint standards
npm run check-lint ||
(
    echo '❌ Failed ESLint check ❌
    Please fix the eslint errors before committing. 
    You can use `npm run lint` to fix the errors, add the changes and commit again.'
    false;
)

# Check Jest standards
npm run test ||
(
    echo '❌ Failed Jest check ❌
    Please fix the jest errors before committing. 
    You can use `npm run test` to fix the errors, add the changes and commit again.'
    false;
)

# If all checks pass, build the project
npm run build ||
(
    echo '❌ Failed Build ❌
    Please fix the build errors before committing. 
    You can use `npm run build` to fix the errors, add the changes and commit again.'
    false;
)

# If build is successful, commit the changes
echo '✅ All checks passed. Committing changes...'